const AUDIT_EVENT_TYPES = Object.freeze({
  ORGANIZATION_BOOTSTRAPPED: 'organization_bootstrapped',
  ORGANIZATION_CREATED: 'organization_created',
  ORGANIZATION_UPDATED: 'organization_updated',
  ORGANIZATION_PLAN_CHANGE_REQUESTED: 'organization_plan_change_requested',
  ORGANIZATION_PLAN_CHANGE_APPROVED: 'organization_plan_change_approved',
  ORGANIZATION_PLAN_CHANGE_REJECTED: 'organization_plan_change_rejected',
  ORGANIZATION_ACTIVATED: 'organization_activated',
  ORGANIZATION_DEACTIVATED: 'organization_deactivated',
  ORGANIZATION_DELETED: 'organization_deleted',
  INVOICE_CREATED: 'invoice_created',
  INVOICE_STATUS_UPDATED: 'invoice_status_updated',
  USER_CREATED: 'user_created',
  USER_UPDATED: 'user_updated',
  USER_ACTIVATED: 'user_activated',
  USER_DEACTIVATED: 'user_deactivated',
  PASSWORD_CHANGED: 'password_changed',
  PROPERTY_CREATED: 'property_created',
  PROPERTY_UPDATED: 'property_updated',
  PROPERTY_DELETED: 'property_deleted',
  TENANT_CREATED: 'tenant_created',
  TENANT_UPDATED: 'tenant_updated',
  TENANT_DELETED: 'tenant_deleted',
  CONTRACT_CREATED: 'contract_created',
  CONTRACT_UPDATED: 'contract_updated',
  CONTRACT_TERMINATED: 'contract_terminated',
  PAYMENT_RECORDED: 'payment_recorded',
  PAYMENT_MARKED_PAID: 'payment_marked_paid',
  EXPENSE_CREATED: 'expense_created',
  EXPENSE_UPDATED: 'expense_updated',
  EXPENSE_DELETED: 'expense_deleted',
  MAINTENANCE_CREATED: 'maintenance_created',
  MAINTENANCE_UPDATED: 'maintenance_updated',
  LAWYER_CREATED: 'lawyer_created',
  LAWYER_UPDATED: 'lawyer_updated',
  LAWYER_DELETED: 'lawyer_deleted',
  LEGAL_CASE_CREATED: 'legal_case_created',
  LEGAL_CASE_UPDATED: 'legal_case_updated',
  LEGAL_CASE_DELETED: 'legal_case_deleted',
  MARKET_PRICE_CREATED: 'market_price_created',
  MARKET_PRICE_UPDATED: 'market_price_updated',
  MARKET_PRICE_DELETED: 'market_price_deleted',
  TAX_CREATED: 'tax_created',
  TAX_UPDATED: 'tax_updated',
  TAX_DELETED: 'tax_deleted',
  DOCUMENT_UPLOADED: 'document_uploaded',
  DOCUMENT_DELETED: 'document_deleted'
});

const AUDIT_EVENT_TYPE_SET = new Set(Object.values(AUDIT_EVENT_TYPES));

const AUDIT_EVENT_LABELS = Object.freeze({
  [AUDIT_EVENT_TYPES.ORGANIZATION_BOOTSTRAPPED]: 'Organizasyon Başlatıldı',
  [AUDIT_EVENT_TYPES.ORGANIZATION_CREATED]: 'Organizasyon Oluşturuldu',
  [AUDIT_EVENT_TYPES.ORGANIZATION_UPDATED]: 'Organizasyon Güncellendi',
  [AUDIT_EVENT_TYPES.ORGANIZATION_PLAN_CHANGE_REQUESTED]: 'Paket Değişikliği Talep Edildi',
  [AUDIT_EVENT_TYPES.ORGANIZATION_PLAN_CHANGE_APPROVED]: 'Paket Değişikliği Onaylandı',
  [AUDIT_EVENT_TYPES.ORGANIZATION_PLAN_CHANGE_REJECTED]: 'Paket Değişikliği Reddedildi',
  [AUDIT_EVENT_TYPES.ORGANIZATION_ACTIVATED]: 'Organizasyon Aktifleştirildi',
  [AUDIT_EVENT_TYPES.ORGANIZATION_DEACTIVATED]: 'Organizasyon Pasife Alındı',
  [AUDIT_EVENT_TYPES.ORGANIZATION_DELETED]: 'Organizasyon Silindi',
  [AUDIT_EVENT_TYPES.INVOICE_CREATED]: 'Fatura Oluşturuldu',
  [AUDIT_EVENT_TYPES.INVOICE_STATUS_UPDATED]: 'Fatura Durumu Güncellendi',
  [AUDIT_EVENT_TYPES.USER_CREATED]: 'Kullanıcı Oluşturuldu',
  [AUDIT_EVENT_TYPES.USER_UPDATED]: 'Kullanıcı Güncellendi',
  [AUDIT_EVENT_TYPES.USER_ACTIVATED]: 'Kullanıcı Aktifleştirildi',
  [AUDIT_EVENT_TYPES.USER_DEACTIVATED]: 'Kullanıcı Pasife Alındı',
  [AUDIT_EVENT_TYPES.PASSWORD_CHANGED]: 'Şifre Değiştirildi',
  [AUDIT_EVENT_TYPES.PROPERTY_CREATED]: 'Mülk Oluşturuldu',
  [AUDIT_EVENT_TYPES.PROPERTY_UPDATED]: 'Mülk Güncellendi',
  [AUDIT_EVENT_TYPES.PROPERTY_DELETED]: 'Mülk Silindi',
  [AUDIT_EVENT_TYPES.TENANT_CREATED]: 'Kiracı Oluşturuldu',
  [AUDIT_EVENT_TYPES.TENANT_UPDATED]: 'Kiracı Güncellendi',
  [AUDIT_EVENT_TYPES.TENANT_DELETED]: 'Kiracı Silindi',
  [AUDIT_EVENT_TYPES.CONTRACT_CREATED]: 'Sözleşme Oluşturuldu',
  [AUDIT_EVENT_TYPES.CONTRACT_UPDATED]: 'Sözleşme Güncellendi',
  [AUDIT_EVENT_TYPES.CONTRACT_TERMINATED]: 'Sözleşme Sonlandırıldı',
  [AUDIT_EVENT_TYPES.PAYMENT_RECORDED]: 'Ödeme Kaydedildi',
  [AUDIT_EVENT_TYPES.PAYMENT_MARKED_PAID]: 'Ödeme Tahsil Edildi',
  [AUDIT_EVENT_TYPES.EXPENSE_CREATED]: 'Gider Oluşturuldu',
  [AUDIT_EVENT_TYPES.EXPENSE_UPDATED]: 'Gider Güncellendi',
  [AUDIT_EVENT_TYPES.EXPENSE_DELETED]: 'Gider Silindi',
  [AUDIT_EVENT_TYPES.MAINTENANCE_CREATED]: 'Bakım Talebi Oluşturuldu',
  [AUDIT_EVENT_TYPES.MAINTENANCE_UPDATED]: 'Bakım Talebi Güncellendi',
  [AUDIT_EVENT_TYPES.LAWYER_CREATED]: 'Avukat Oluşturuldu',
  [AUDIT_EVENT_TYPES.LAWYER_UPDATED]: 'Avukat Güncellendi',
  [AUDIT_EVENT_TYPES.LAWYER_DELETED]: 'Avukat Silindi',
  [AUDIT_EVENT_TYPES.LEGAL_CASE_CREATED]: 'Dava Oluşturuldu',
  [AUDIT_EVENT_TYPES.LEGAL_CASE_UPDATED]: 'Dava Güncellendi',
  [AUDIT_EVENT_TYPES.LEGAL_CASE_DELETED]: 'Dava Silindi',
  [AUDIT_EVENT_TYPES.MARKET_PRICE_CREATED]: 'Fiyat Kaydı Oluşturuldu',
  [AUDIT_EVENT_TYPES.MARKET_PRICE_UPDATED]: 'Fiyat Kaydı Güncellendi',
  [AUDIT_EVENT_TYPES.MARKET_PRICE_DELETED]: 'Fiyat Kaydı Silindi',
  [AUDIT_EVENT_TYPES.TAX_CREATED]: 'Vergi Kaydı Oluşturuldu',
  [AUDIT_EVENT_TYPES.TAX_UPDATED]: 'Vergi Kaydı Güncellendi',
  [AUDIT_EVENT_TYPES.TAX_DELETED]: 'Vergi Kaydı Silindi',
  [AUDIT_EVENT_TYPES.DOCUMENT_UPLOADED]: 'Belge Yüklendi',
  [AUDIT_EVENT_TYPES.DOCUMENT_DELETED]: 'Belge Silindi'
});

module.exports = {
  AUDIT_EVENT_TYPES,
  AUDIT_EVENT_TYPE_SET,
  AUDIT_EVENT_LABELS
};